# Generated by Django 5.1.12 on 2025-10-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_loanrepayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan"),
                            ("deduction", "Deduction"),
                            ("repayment", "Repayment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                (
                    "related_loan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the original loan if this is a repayment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.loan",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_transactions",
                        to="users.staff",
                    ),
                ),
            ],
        ),
    ]
