# Generated by Django 5.1.12 on 2025-10-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_migrate_financial_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanrepayment",
            name="loan",
        ),
        migrations.DeleteModel(
            name="Deduction",
        ),
        migrations.DeleteModel(
            name="LoanRepayment",
        ),
    ]
