# Generated by Django 5.1.1 on 2024-10-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_orderstatus_supplier_inventory_inhold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
    ]
