# Generated by Django 5.1.1 on 2024-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_rename_first_name_staff_name_remove_staff_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(default='All Week', max_length=100),
        ),
    ]
