# Generated by Django 5.1.1 on 2024-10-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_extra_extraitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraitem',
            name='order',
        ),
    ]
