# Generated by Django 5.1.1 on 2024-10-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_remove_extraitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
