# Generated by Django 5.1.1 on 2024-11-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_staff_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.ManyToManyField(blank=True, to='item.extra'),
        ),
    ]
