# Generated by Django 5.1.1 on 2024-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_orderitem_extras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='extras',
            new_name='selected_extras',
        ),
        migrations.AddField(
            model_name='item',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='items', to='item.extra'),
        ),
        migrations.DeleteModel(
            name='ExtraItem',
        ),
    ]
