# Generated by Django 5.1.1 on 2024-12-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_orderstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[('readytoprint', 'Ready to Print'), ('printed', 'Printed'), ('completed', 'Completed'), ('pending', 'Pending'), ('delivered', 'Delivered')], default='readytoprint', max_length=100),
        ),
    ]
