# Generated by Django 5.1.1 on 2025-01-03 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_table_alter_orderstatus_options_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
