# Generated by Django 5.1.5 on 2025-03-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0024_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[('readytoprint', 'Ready to Print'), ('printed', 'Printed'), ('completed', 'Completed'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('served', 'Served')], default='readytoprint', max_length=100),
        ),
    ]
