# Generated by Django 5.2.1 on 2025-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_alter_orderstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[('readytoprint', 'Ready to Print'), ('printed', 'Printed'), ('printing', 'Printing'), ('completed', 'Completed'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('served', 'Served')], default='readytoprint', max_length=100),
        ),
    ]
