# Generated by Django 5.1.1 on 2025-07-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_invoice_inhold_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
