# Generated by Django 5.1.1 on 2025-07-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
