# Generated by Django 5.1.1 on 2025-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0032_alter_invoice_options_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='inHold',
            field=models.BooleanField(default=False),
        ),
    ]
