# Generated by Django 5.1.1 on 2025-07-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0033_payment_inhold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='inHold',
        ),
    ]
