# Generated by Django 5.1.1 on 2025-07-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0034_remove_payment_inhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='inHold',
            field=models.BooleanField(default=False),
        ),
    ]
