# Generated by Django 5.1.1 on 2025-07-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0036_unpaidreasonlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_taken', to='item.staff'),
        ),
    ]
