# Generated by Django 5.1.1 on 2025-07-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0038_remove_staff_waiter_order_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
