# Generated by Django 5.1.1 on 2025-07-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0039_dailyordercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
