# Generated by Django 5.1.1 on 2025-07-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0040_order_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='item.invoice'),
        ),
    ]
