# Generated by Django 5.1.1 on 2025-07-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0041_orderitem_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
