# Generated by Django 5.1.1 on 2025-07-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0042_remove_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='display_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
