# Generated by Django 5.1.1 on 2025-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0043_invoice_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
