# Generated by Django 5.1.1 on 2025-07-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0044_order_previous_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
    ]
