# Generated by Django 5.1.1 on 2025-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0047_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOMO', 'Momo'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=15),
        ),
    ]
