# Generated by Django 5.1.1 on 2025-08-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0048_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('chef', 'Chef'), ('waiter', 'Waiter'), ('manager', 'Manager'), ('admin', 'Admin'), ('cashier', 'Cashier'), ('cleaner', 'Cleaner'), ('barista', 'Barista')], max_length=50),
        ),
    ]
