# Generated by Django 5.1.1 on 2025-08-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Mocah Cafe", max_length=255)),
                ("logo", models.ImageField(upload_to="branding/")),
                ("slogan", models.CharField(blank=True, max_length=255, null=True)),
                ("primary_color", models.CharField(default="#FF5733", max_length=7)),
                ("secondary_color", models.CharField(default="#33FF57", max_length=7)),
            ],
        ),
    ]
