# Generated by Django 5.1.1 on 2025-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantconfig",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AlterField(
            model_name="restaurantconfig",
            name="slogan",
            field=models.CharField(
                default="Memories of joy and happiness.", max_length=255
            ),
        ),
    ]
