from django.urls import path

from . import views

urlpatterns =[
    path('',views.index,name='index'),
    path('meal/<int:menu_item_id>/',views.orderPage,name='orderPage'),
    path('get-extras/<int:menu_item_id>/', views.get_extras, name='get_extras'),
    path('order_details/', views.orderDetails, name='orderDetails'),
    path('order_details_api/<int:order_id>/', views.orderDetailApi, name='orderDetailsApi'),
    path('order_view/<int:order_id>/',views.orderView , name='orderView'),
    path('orders/', views.orderList, name='orderList'),
    path('add_to_order/', views.addToOrder, name='add_to_order'),
    path('order_details/delete_item/<int:item_id>/', views.delete_order_item, name='delete_order_item'),
    path('submit_order/', views.submitOrder, name='submit_order'),
    path('print_order/', views.printOrder, name='print_order'),
    path('login/', views.login_view, name='login'),
    path('admin_dashboard/', views.adminDashboard, name='admin_dashboard'),  # Example redirect
 #   path('customer_home/', views.customer_home, name='customer_home'),  
    path('customer_signup/', views.customerSignup, name='customer_signup'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.customerProfile, name='customer_profile'),
    path('delete_order/<int:order_id>/', views.deleteOrder, name='delete_order'),
    path('update_order_status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('print_order_view/<int:order_id>/', views.print_order_view, name='print_order'),
    path('move_table_view/', views.moveTable, name='move_table_view'),
    path('generate_invoice/<int:table_id>/', views.generate_invoice, name='generate_invoice'),  
    path('generate-invoice-by-table/', views.generate_invoice_by_table, name='generate_invoice_table'),
    path('generate-invoice-by-item/', views.generateInvoiceByItem, name='generate_invoice_item'),
    path('invoices/', views.invoice_dashboard, name='invoice_dashboard'),
    path('invoice/<int:invoice_id>/', views.view_invoice, name='view_invoice'),
    path('invoiceA4/<int:invoice_id>/', views.view_invoiceA4, name='view_invoice_A4'),
    path("invoice/<int:invoice_id>/update-status/", views.update_invoice_status, name="update_invoice_status"),
    path("invoice/<int:invoice_id>/pay/", views.process_payment, name="process_payment"),
    path('mark-unpaid/', views.mark_unpaid, name='mark_unpaid'),
    path('print_invoice/<int:invoice_id>/', views.print_invoice_view, name='print_invoice'),  
    path('sales_report/', views.sales_report, name='sales_report'),
    path('tables/', views.table_dashboard, name='table_dashboard'),
    path('tables/<int:table_id>/update/', views.update_table_status, name='update_table_status'),
    path('tables/<int:table_id>/delete/', views.delete_table, name='delete_table'),
    path('tables/<int:table_id>/edit/', views.edit_table, name='edit_table'),
    path('tables/<int:table_id>/history/', views.get_table_history, name='get_table_history'),
    path('order/update-item/', views.updateOrderItem, name='update_order_item'),
    path('order_detail/empty_order/', views.emptyOrder, name='empty_order_item'),
    path('set_table/', views.setTableNumber, name='set_table_number'),
    path('table_landing/', views.tableLanding, name='table_landing_page'),
    path('get_order_by_table/<int:table_id>/',views.getOrderByTable , name='get_order_by_table'),
    path('cancelled_orders/', views.cancelled_orders, name='cancelled_orders'),
]