# Generated by Django 5.1.1 on 2025-08-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "__first__"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="payments.invoice",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.item",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="selected_extras",
            field=models.ManyToManyField(blank=True, to="menu.extra"),
        ),
        migrations.AddField(
            model_name="orderitemextra",
            name="extra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.extra",
            ),
        ),
        migrations.AddField(
            model_name="orderitemextra",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.orderitem"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.orderstatus",
            ),
        ),
    ]
