# Generated by Django 5.1.1 on 2025-08-23 19:42

from django.db import migrations

SQL_COMMANDS = """
SELECT setval(pg_get_serial_sequence('users_staff', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM users_staff;
SELECT setval(pg_get_serial_sequence('users_customer', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM users_customer;
SELECT setval(pg_get_serial_sequence('menu_item', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM menu_item;
SELECT setval(pg_get_serial_sequence('menu_category', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM menu_category;
SELECT setval(pg_get_serial_sequence('menu_extra', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM menu_extra;
SELECT setval(pg_get_serial_sequence('orders_orderstatus', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM orders_orderstatus;
SELECT setval(pg_get_serial_sequence('orders_order', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM orders_order;
SELECT setval(pg_get_serial_sequence('orders_orderitem', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM orders_orderitem;
SELECT setval(pg_get_serial_sequence('orders_orderitemextra', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM orders_orderitemextra;
SELECT setval(pg_get_serial_sequence('orders_dailyordercounter', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM orders_dailyordercounter;
SELECT setval(pg_get_serial_sequence('orders_discount', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM orders_discount;
SELECT setval(pg_get_serial_sequence('reservations_table', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM reservations_table;
SELECT setval(pg_get_serial_sequence('reservations_reservation', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM reservations_reservation;
SELECT setval(pg_get_serial_sequence('payments_invoice', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM payments_invoice;
SELECT setval(pg_get_serial_sequence('payments_payment', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM payments_payment;
SELECT setval(pg_get_serial_sequence('payments_unpaidreasonlog', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM payments_unpaidreasonlog;
SELECT setval(pg_get_serial_sequence('inventory_inventory', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM inventory_inventory;
SELECT setval(pg_get_serial_sequence('inventory_supplier', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM inventory_supplier;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('reservations', '0001_initial'),
        ('payments', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(SQL_COMMANDS, reverse_sql=migrations.RunSQL.noop),
    ]