# Generated by Django 5.1.1 on 2025-08-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('orders', '0003_auto_20250823_2158'),
    ]

    operations = [
    ]
