# Generated by Django 5.1.1 on 2025-08-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('orders', '0003_auto_20250822_1738'),
    ]

    operations = [
    ]
