# Generated by Django 5.1.1 on 2025-09-24 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_reset_all_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='inHold',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[('readytoprint', 'Ready to Print'), ('printed', 'Printed'), ('printing', 'Printing'), ('completed', 'Completed'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('served', 'Served')], db_index=True, default='readytoprint', max_length=100),
        ),
    ]
