# Generated by Django 5.1.12 on 2025-10-06 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_deleted_at_alter_order_inhold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='inHold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[('readytoprint', 'Ready to Print'), ('printed', 'Printed'), ('printing', 'Printing'), ('completed', 'Completed'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('served', 'Served')], default='readytoprint', max_length=100),
        ),
    ]
