# Generated by Django 5.1.1 on 2025-08-28 21:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branding",
            name="secondary_color",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="branding",
            name="slogan",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
