# Generated by Django 5.1.1 on 2025-08-30 17:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0002_branding_secondary_color_branding_slogan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branding",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="branding",
            name="primary_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="secondary_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#000000",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="branding",
            name="slogan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
