# Generated by Django 5.1.1 on 2025-09-06 04:36

from django.db import migrations

def create_default_branding(apps, schema_editor):
    Branding = apps.get_model('theme', 'Branding')
    Branding.objects.create(
        name='Default Settings',
        primary_color='#d54b27',
        secondary_color='#ffa012',
        slogan='Memories of joy and happiness',
        logo=None
    )

class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_branding_logo_alter_branding_primary_color_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_branding),
    ]
