# Generated by Django 5.1.1 on 2025-09-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0004_create_default_branding_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="branding",
            name="is_default_profile",
            field=models.BooleanField(default=False),
        ),
    ]
