# Generated by Django 5.1.1 on 2025-09-09 05:16

from django.db import migrations

def set_initial_flags(apps, schema_editor):
    Branding = apps.get_model('theme', 'Branding')

    # Set the 'Default Settings' profile
    try:
        default_profile = Branding.objects.get(name='Default Settings')
        default_profile.is_default_profile = True
        default_profile.is_active = False
        default_profile.save()
    except Branding.DoesNotExist:
        # If it doesn't exist, we can create it, but the previous migration should have done that.
        # We'll create it here just in case to be robust.
        Branding.objects.create(
            name='Default Settings',
            is_default_profile=True,
            is_active=False,
            primary_color='#d54b27',
            secondary_color='#ffa012',
            slogan='Memories of joy and happiness',
        )

    # Set the active profile
    # We assume the profile that is not the default one is the active one.
    active_profile = Branding.objects.filter(is_default_profile=False).first()
    if active_profile:
        active_profile.is_active = True
        active_profile.save()
    else:
        # If for some reason there is no active profile, create one.
        # This is a fallback.
        Branding.objects.get_or_create(
            name='Mocha Cafe',
            defaults={'is_active': True}
        )


def unset_initial_flags(apps, schema_editor):
    # This is the reverse operation. We don't need to do anything here.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_branding_is_active_branding_is_default_profile'),
    ]

    operations = [
        migrations.RunPython(set_initial_flags, reverse_code=unset_initial_flags),
    ]
