# Generated by Django 5.1.1 on 2025-09-06 04:55

from django.db import migrations

def set_default_profile_flag(apps, schema_editor):
    Branding = apps.get_model('theme', 'Branding')
    try:
        default_branding = Branding.objects.get(name='Default Settings')
        default_branding.is_default_profile = True
        default_branding.save()
    except Branding.DoesNotExist:
        # If the 'Default Settings' profile does not exist for some reason,
        # we can create it here, or just do nothing.
        # For now, we will do nothing.
        pass

def unset_default_profile_flag(apps, schema_editor):
    # This is the reverse operation. We can choose to do nothing here,
    # as setting the flag to False is not strictly necessary.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_branding_is_default_profile'),
    ]

    operations = [
        migrations.RunPython(set_default_profile_flag, reverse_code=unset_default_profile_flag),
    ]
