# Generated by Django 5.1.1 on 2025-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0006_set_default_profile_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="branding",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
