# Generated by Django 5.1.1 on 2025-09-07 03:09

from django.db import migrations

def set_active_profile_flag(apps, schema_editor):
    Branding = apps.get_model('theme', 'Branding')
    # We assume that the profile that is NOT the default one is the active one.
    # This is a one-time operation to set the initial state.
    active_profile = Branding.objects.filter(is_default_profile=False).first()
    if active_profile:
        active_profile.is_active = True
        active_profile.save()

def unset_active_profile_flag(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_branding_is_active'),
    ]

    operations = [
        migrations.RunPython(set_active_profile_flag, reverse_code=unset_active_profile_flag),
    ]
